### ISSUE TITLE
Conflict with Visual Studio's integrated support for markdown files

### ISSUE THREAD

**Issue by OJacot-Descombes** [NeVeSpl/MermaidEditorForVisualStudio#1]
I have Visual Studio 17.5.3. It has an integrated support for *.md files.

It opens *.mmd files in the markdown editor as well but does not support mermaid syntax. The MermaidEditorForVisualStudio does not open! I think markdown is supported since VS 17.5.2

Possible resolution: Associate Mermaid Editor with other file extensions as well (e.g. *.mm or *.mermaid)

**Comment by NeVeSpl** [comment]
I have updated my VS from 17.5.1 to 17.5.3, and the built-in markdown editor is associated with:
![image](https://user-images.githubusercontent.com/11632757/230902225-55f10b5c-8765-4572-879a-22d7e999b31b.png)
I do not see *.mmd on that list, but sure, we can add support for more file extensions.

**Comment by OJacot-Descombes** [comment]
Thanks. My guess is that Visual Studio tests for the ending "md" instead of ".md" (with a dot). I made a file *.xmd and the markdown editor opens it.
