### ISSUE TITLE
Add Contributions Guide and Developer Getting Started Instructions

### ISSUE THREAD

**Issue by ReneLombard** [NeVeSpl/MermaidEditorForVisualStudio#10]
It would be awesome if we could expand this project with more contributors, however, it is not clear how to go about adding a contribution and how to get the environment up and running,

Maybe it is an idea to add this to the project so that other people can build on your project

**Comment by NeVeSpl** [comment]
It is a very simple project, everything should work out of the box after downloading source code.

All PR are welcome, there are no rules or protocol regarding contribution.
