### ISSUE TITLE
note over A

### ISSUE THREAD

**Issue by MrBjorn** [NeVeSpl/MermaidEditorForVisualStudio#7]
I have a note in a sequence diagram, and the surrounding yellow box is a bit to small. Something like this:

note over A: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam leo nunc, tempus sed accumsan a, facilisis consequat ante. Praesent lacinia eleifend euismod.

**Comment by NeVeSpl** [comment]
I am not sure what is your problem, but it sounds more like smth related to mermaid.js and not this addin.
